
#ifndef ACMCONFIG_H
#define ACMCONFIG_H


#define VVVF_CONTROL 0
#define IFOC 1
#define DFOC 2

#define TAJIMA96 0 
#define TOTALLY_ADAPTIVE_OBSERVER 1 // Flux-MRAS
#define FIRST_APPROXIMATION_ANDERSON86 2

#define NUMBER_OF_STEPS 750000
#define DOWN_SAMPLE 1
#define CONTROL_STRATEGY IFOC
#define OBSERVER_APPLIED FIRST_APPROXIMATION_ANDERSON86
#define SENSORLESS_CONTROL True
#define VOLTAGE_CURRENT_DECOUPLING_CIRCUIT False
#define SATURATED_MAGNETIC_CIRCUIT False
#define INVERTER_NONLINEARITY False
#define TS 0.00025
#define TS_INVERSE 4000
#define TS_UPSAMPLING_FREQ_EXE 0.5
#define TS_UPSAMPLING_FREQ_EXE_INVERSE 2
#define IM_NUMBER_OF_POLE_PAIRS 2
#define IM_STATOR_RESISTANCE 3.04
#define IM_INVERSE_GAMMA_CIRCUIT_MAGNETIZING_INDUCTANCE 0.4482
#define IM_INVERSE_GAMMA_CIRCUIT_ROTOR_RESISTANCE 1.69
#define IM_T_CIRCUIT_STATOR_LEAKAGE_INDUCTANCE 0.0126
#define IM_T_CIRCUIT_ROTOR_LEAKAGE_INDUCTANCE 0.0126
#define IM_SHAFT_INERTIA 0.0636
#define SPEED_LOOP_PID_PROPORTIONAL_GAIN 0.5
#define SPEED_LOOP_PID_INTEGRAL_TIME_CONSTANT 1.05
#define SPEED_LOOP_PID_DIREVATIVE_TIME_CONSTANT 0
#define SPEED_LOOP_LIMIT_NEWTON_METER 8
#define SPEED_LOOP_CEILING 40
#define CURRENT_LOOP_PID_PROPORTIONAL_GAIN 15
#define CURRENT_LOOP_PID_INTEGRAL_TIME_CONSTANT 0.08
#define CURRENT_LOOP_PID_DIREVATIVE_TIME_CONSTANT 0
#define CURRENT_LOOP_LIMIT_VOLTS 650
#define DATA_FILE_NAME "im_taa86.dat"
#define PC_SIMULATION True


#define MACHINE_TS         (TS*TS_UPSAMPLING_FREQ_EXE) //1.25e-4 
#define MACHINE_TS_INVERSE (TS_INVERSE*TS_UPSAMPLING_FREQ_EXE_INVERSE) // 8000

#endif
