
#ifndef ACMCONFIG_H
#define ACMCONFIG_H

#define NULL_D_AXIS_CURRENT_CONTROL -1
#define MTPA -2 // not supported

#define NUMBER_OF_STEPS 150000
#define DOWN_SAMPLE 1
#define CONTROL_STRATEGY NULL_D_AXIS_CURRENT_CONTROL
#define SENSORLESS_CONTROL False
#define VOLTAGE_CURRENT_DECOUPLING_CIRCUIT False
#define SATURATED_MAGNETIC_CIRCUIT False
#define INVERTER_NONLINEARITY False
#define MACHINE_TS 0.000125
#define MACHINE_TS_INVERSE 8000
#define DOWN_FREQ_EXE 2
#define DOWN_FREQ_EXE_INVERSE 0.5
#define PMSM_NUMBER_OF_POLE_PAIRS 2
#define PMSM_RESISTANCE 0.45
#define PMSM_D_AXIS_INDUCTANCE 0.00415
#define PMSM_Q_AXIS_INDUCTANCE 0.01674
#define PMSM_PERMANENT_MAGNET_FLUX_LINKAGE 0.504
#define PMSM_SHAFT_INERTIA 0.06
#define PC_SIMULATION True

#define TS (MACHINE_TS*DOWN_FREQ_EXE) //2.5e-4 
#define TS_INVERSE (MACHINE_TS_INVERSE*DOWN_FREQ_EXE_INVERSE) // 4000

#endif
